#.travis.yml

language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run prod

after_success:

notifications:
  email:
    on_failure: change
    on_success: change
