language: node_js
node_js:
- '8.9'
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
script:
- ng build --prod
- cat src/environment/environment.prod.ts
- npm run test
after_success:
notifications:
  email:
    on_failure: change
    on_success: change
env:
  global:
    secure: DrHqW7AEEGFXC8QcdezOWX79vn37PFDgk1+GSJwLAoEFva/kUm/F1fY8i0aDYpJdQdeCrm9EtQDN/XzzkN9bZ2iDt9tCwRu3thNwAcQMaZbWGJGUOFT6PcU7lG1tGDexOmwzkTuQE8bvh6l8w5aTD7SCINbak+OTpujt4IdQZBQnja56DV03AxAM+VGrTIgcAUkv2NtPgDnWD8ig3BEN0lZ/yKmxsbX610zibdXcJxmaWxkJqYFrCXJMwgOoLluv2/7/SvQ7M742s9z/1dHhD5ITJV4sUfUkJ/UUX5cPjJV41MHhcdrWNItvUlrfCVRiwVH9VcGY3g2ZybnQpHUHEfgl3Pp1l4ndLxKGSqJTxZoNMk4R6rP4x3KIbxYOr4WoSjz6k+oYFXc6eGGn5ZBoFChKTu1XTuZ6bLki35L5+xzjyZdOrcfXZoa5TvziTvRZGzXtzr/h34s1ghl9UVk9843zdwaI/n22MkGsGrq6XXVnLdY+/rpbp8S1eTAf9c5m4W4CzD24ixHj8nj+ojPmttB6NN5ApRCFqmI7uGPzFeXEsQD0sYYn29iDP7OmMSaKeVjgtrw1b2dq7e79WwGkUZUitloMTUX13Z71f6jSzXr1nOh10aUjPU6DFfOYSnnbbMvfi3M9AgiOKYu5YBJSDYLc07z9AASn9eBzljBZcB4=
